[Include]
Include=../../modules/build/host

[Distribution]
Distribution=debian
Release=trixie

[Content]
Packages=
	linux-image-amd64
	systemd
	systemd-boot
	systemd-boot-efi
	systemd-resolved
	login.defs
	login
	locales
	systemd-journal-remote
	qemu-system
	apt
	ovmf
	net-tools
	openssh-server
	xxd
	python3
	python3-pip
	python3-cryptography
	python3-emoji
	jq
	avahi-daemon

[Build]
Environment=VERSION="13"
