[Include]
Include=../../modules/build/host

[Distribution]
Distribution=rocky
Release=10
RepositoryKeyFetch=yes

[Content]
Packages=
	 kernel
	 systemd
	 systemd-boot-unsigned
     systemd-resolved
	 qemu-kvm-core
	 edk2-ovmf
	 dnf
	 rpm
	 systemd-journal-remote
	 xxd
	 python3
	 python3-pip
	 python3-cryptography
	 jq
	 avahi
