[Include]
Include=../../modules/build/host

[Distribution]
Distribution=opensuse
Release=16.0
RepositoryKeyFetch=yes

[Content]
Packages=
        kernel-default
        systemd
        systemd-boot
        systemd-networkd
        systemd-resolved
        zypper
        ca-certificates
        p11-kit-tools
        patterns-devel-base-devel_basis
        NetworkManager
        SUSEConnect
        shadow
        qemu
        qemu-ovmf-x86_64
        kernel
        rpm
        systemd-journal-remote
        xxd
        python3
        python3-pip
        python3-cryptography
        python3-emoji
        jq
        avahi
KernelCommandLine="iommu=nopt"

[Build]
Environment=VERSION="16.0"
SandboxTrees=mkosi.pkgmngr
